#!/usr/bin/env python
######################################################################
## AUSTRALIAN BUREAU OF METEOROLOGY
## BUREAU NATIONAL OPERATIONS CENTRE
## SECTION: OCEANOGRAPHIC SYSTEMS DEVELOPMENT SECTION
##
## DATE:         Dec 2015
## AUTHOR:       Robert Johnson rjohnson@bom.gov.au
## VERSION:      0.01
## LANGUAGE:     Python
##
## USAGE:       python pull.py <date>
##
## PURPOSE:     This script reads from the url catalog defined in the config.env
##              file - the one generated by the eReefs_tds_crawler.py script -
##              and then pulls down the relevent .nc files for the days you list
##              as an input. - it puts the data in the DATA_DIR.
##
##              python pull.py 2015051
##
## N.B:         This code expects that you've sourced the projects config.env
##
##
######################################################################

######################################################################
# set up your environment.
######################################################################
import simplejson
import os
import urllib
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("date", help="This is the date string that you're looking to find matching files for.")
args = parser.parse_args()
# print args.date

DATA_DIR=os.environ.get('DATA_DIR')
URL_FILE=os.environ.get('URL_FILE')

# load the urls.
with open(URL_FILE) as f:
    eReefs_data_urls = simplejson.load(f)

# Load the dates
date_of_interest=args.date
print "######################################################################"
print "                      Starting the pull.py script."
print ""
# find the urls that have these dates.
matching_urls = [tmp1 for tmp1 in eReefs_data_urls if date_of_interest in tmp1]
print "Found ", len(matching_urls), " matching file url(s)."

print "Pulling your files... this might take a while..."

testfile = urllib.URLopener()
for url in matching_urls:
    print "Downloading: " + url
    testfile.retrieve(url, os.path.join(DATA_DIR, os.path.basename(url)))


print "                           Finshed."
print "######################################################################"

#
# # set up the spatial boundaries of each corner of the plot:
# LONMIN=145 ; LONMAX=151 # Longitude range of plots
# LATMIN=-21 ; LATMAX=-15.5 # Latitude range of plots
